apiVersion: apps/v1
kind: Deployment
metadata:
  name: appteam1
spec:
  replicas: 2
  paused: false
  selector:
    matchLabels:
      app: appteam1
  template:
    metadata:
      labels:
        app: appteam1
    spec:
      containers:
      - name: appteam1
        image: fd860fbe3a518dbcd05c7b73e1feee5766aafe80
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: appteam1-service
spec:
  selector:
    app: appteam1
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
