apiVersion: apps/v1
kind: Deployment
metadata:
  name: appteam1testing
spec:
  replicas: 0
  paused: false
  selector:
    matchLabels:
      app: appteam1testing
  template:
    metadata:
      labels:
        app: appteam1testing
    spec:
      containers:
      - name: appteam1testing
        image: apistoneteam1.azurecr.io/sampleapp:df7e5195929feb0f6cbd05ec6992d698895c2b98
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: appteam1testing-service
spec:
  selector:
    app: appteam1testing
  type: LoadBalancer
  ports:
  - port: 8181
    targetPort: 80
