apiVersion: apps/v1
kind: Deployment
metadata:
  name: appteam1testing
spec:
  replicas: 1
  paused: false
  selector:
    matchLabels:
      app: appteam1testing
  template:
    metadata:
      labels:
        app: appteam1testing
    spec:
      containers:
      - name: appteam1testing
        image: apistoneteam1.azurecr.io/sampleapp:fd860fbe3a518dbcd05c7b73e1feee5766aafe80
        resources:
          limits:
            memory: "800Mi"
            cpu: "800m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: appteam1testing-service
spec:
  selector:
    app: appteam1testing
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
