on:
  push:
    branches: [dev]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}

        - name: Azure login
          id: login
          uses: azure/login@v1.4.3
          with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: Set AKS context
          id: set-context
          uses: azure/aks-set-context@v3
          with:
            resource-group: APISTONE 
            cluster-name: team1apistone
        - name: Setup kubectl
          id: install-kubectl
          uses: azure/setup-kubectl@v3
        - name: Create namespace
          run: |
            namespacePresent='kubectl get namespace | grep dev | wx -l'
            if [ $namespacePresent -eq 0 ]
            then
              echo 'kubectl create namespace dev'
            fi
        - uses: azure/k8s-create-secret@v1
          with:
            namespace: dev
            container-registry-url: apistoneteam1.azure.io
            container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
            container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secret-name: kuber
            
        - uses: azure/k8s-deploy@v1
          with: 
            namespace: dev
            manifests: k8s/deployment.yml
            images: apistoneteam1.azurecr.io/sampleapp:${{ github.sha }}
            imagepullsecrets: |
              kuber
            
            
            
            
        
